# Generated by Django 3.2.16 on 2023-01-04 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branches',
            name='img',
        ),
        migrations.RemoveField(
            model_name='branches',
            name='name',
        ),
        migrations.RemoveField(
            model_name='branches',
            name='slug',
        ),
    ]
