# Generated by Django 3.2.16 on 2023-01-04 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230104_1121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branches',
        ),
    ]
